repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: insert-license
        files: \.go$
        args:
          - --license-filepath
          - license_header.txt
          - --comment-style
          - //   
          - --use-current-year
          - --no-extra-eol