apiVersion: v1
kind: Pod
metadata:
  generateName: pod-
spec:
  restartPolicy: OnFailure
  containers:
  - image: ubuntu
    name: pod1-ctr
    command: ["sleep"]
    args: ["infinity"]
    resources:
      requests:
        birentech.com/gpu: 4
      limits:
        birentech.com/gpu: 4
        # birentech.com/1-4-gpu: 1
        # birentech.com/1-2-gpu: 1
